### ISSUE TITLE
Help with establishing connection

### ISSUE THREAD

**Issue by pranaviyer24** [kevin-cgc/questxr-happlay#1]
Hello @kevin-cgc 

I am new to XR development and am trying to play haptic patterns on Quest 3 for a research project. I have the server and ngrok proxy running on my laptop after following the documentation however I am unable to run the patterns. Do I need to do anything on the quest headset to make it connect to the ngrok domain since I am not seeing any requests being sent at the moment? 

Any help would be appreciated,
Thanks

**Comment by kevin-cgc** [comment]
If you built the quest app, setting the correct `WS_SERVER_DOMAIN` in `local.properties` file (https://github.com/kevin-cgc/questxr-happlay#building-the-quest-app), it should connect without any input after starting the application.

There is a script to build, deploy to device, and watch the logs for the quest application, which may be helpful in debugging: https://github.com/kevin-cgc/questxr-happlay/blob/main/build-run-watch.sh

**Comment by kevin-cgc** [comment]
Also, if you are having issues building the android project, there is a github action for this (https://github.com/kevin-cgc/questxr-happlay/blob/main/.github/workflows/debugbuild.yml). 

It should be possible to use something like https://github.com/nektos/act to complete the build locally (after replacing the default WS_SERVER_DOMAIN in the action).

**Comment by pranaviyer24** [comment]
Thank you for your response!
You have cleared my confusion, I will try these out
